In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [10]:
# Definiamo le colonne che dovrebbero essere numeriche
numeric_cols = ["Age", "Sleep Duration", "Physical Activity Level",
"Stress Level", "Heart Rate", "Daily Steps"]
# Convertiamo queste colonne in tipo numerico, sostituendo eventuali valori
# non convertibili con NaN (errors="coerce")
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce")

# Sleep Disorder: stringa, nessun NaN
df["Sleep Disorder"] = df["Sleep Disorder"].fillna("None").astype(str)

# Separiamo la colonna "Blood Pressure" in Sistolica e Diastolica
bp_split = df["Blood Pressure"].str.split("/", expand=True)

df["Systolic"] = pd.to_numeric(bp_split[0])
df["Diastolic"] = pd.to_numeric(bp_split[1])

In [ ]:
media_sex = df.groupby("Gender")["Sleep Duration"].mean()
media_sex

Gender
Female    7.229730
Male      7.036508
Name: Sleep Duration, dtype: float64

In [19]:
sleep_apnea = df["Sleep Disorder"].value_counts().loc[["Sleep Apnea", "None"]]
sleep_apnea

Sleep Disorder
Sleep Apnea     78
None           219
Name: count, dtype: int64